export const config = {
    leetcodeTagsMapping: {
        "Array": "array",
        "String": "string",
        "Hash Table": "hash_table",
        "Linked List": "linked_list",
        "Math": "math",
        "Recursion": "recursion",
        "Sliding Window": "sliding_window",
        "Binary Search": "binary_search",
        "Divide and Conquer": "divide_and_conquer",
        "Two Pointers": "two_pointers",
        "Dynamic Programming": "dp",
        "Greedy": "greedy",
        "Trie": "trie",
        "Sorting": "sorting",
        "Backtracking": "backtracking",
        "Stack": "stack",
        "Heap (Priority Queue)": "heap_priority_queue",
        "Merge Sort": "merge_sort",
        "String Matching": "string_matching",
        "Bit Manipulation": "bit_manipulation",
        "Matrix": "matrix",
        "Monotonic Stack": "monotonic_stack",
        "Simulation": "simulation",
        "Combinatorics": "combinatorics",
        "Memoization": "memoization",
        "Depth-First Search": "dfs",
        "Tree": "trees",
        "Binary Tree": "binary_tree",
        "Binary Search Tree": "binary_search_tree",
        "Breadth-First Search": "bfs",
        "Union Find": "union_find",
        "Graph": "graphs",
        "Design": "design",
        "Number Theory": "number_theory",
        "Geometry": "geometry",
        "Interactive": "interactive",
        "Bitmask": "bitmask",
        "Probability and Statistics": "probability_and_statistics",
        "Shortest Path": "shortest_path",
        "Doubly-Linked List": "doubly_linked_list",
        "Bucket Sort": "bucket_sort",
        "Radix Sort": "radix_sort",
        "Counting": "counting",
        "Data Stream": "data_stream",
        "Iterator": "iterator",
        "Database": "database",
        "Rolling Hash": "rolling_hash",
        "Hash Function": "hash_function",
        "Shell": "shell",
        "Enumeration": "enumeration",
        "Topological Sort": "topological_sort",
        "Prefix Sum": "prefix_sum",
        "Quickselect": "quickselect",
        "Binary Indexed Tree": "binary_indexed_tree",
        "Segment Tree": "segment_tree",
        "Line Sweep": "line_sweep",
        "Ordered Set": "ordered_set",
        "Queue": "queue",
        "Monotonic Queue": "monotonic_queue",
        "Counting Sort": "counting_sort",
        "Brainteaser": "brainteaser",
        "Game Theory": "game_theory",
        "Eulerian Circuit": "eulerian_circuit",
        "Randomized": "randomized",
        "Reservoir Sampling": "reservoir_sampling",
        "Rejection Sampling": "rejection_sampling",
        "Suffix Array": "suffix_array",
        "Concurrency": "concurrency",
        "Minimum Spanning Tree": "minimum_spanning_tree",
        "Biconnected Component": "biconnected_component",
        "Strongly Connected Component": "strongly_connected_component"
    },
}